### ISSUE TITLE
cart button on home page does not function

### ISSUE THREAD

**Issue by Volatar** [Volatar/Bombastic-Bookstore#22]
In the new loginv2 branch (soon to be the new main) the cart button on the site homepage does not send you to the cart.

![image](https://github.com/Volatar/Bombastic-Bookstore/assets/1719182/e7b447f1-9345-4f11-80f8-4431be7d29a3)

**Comment by StefanSlaczka** [comment]
add a different way to implement a cart link just press cart.
here is the branch 
https://github.com/Volatar/Bombastic-Bookstore/tree/Stefan-branch

![Screenshot 2024-04-03 193607](https://github.com/Volatar/Bombastic-Bookstore/assets/78507059/370928da-8232-4e29-b174-8c2e03082de5)
